name: airwatch_socket_workaround
description: A workaround for AirWatch MDM Socket problem using dart sockets
version: 0.0.1
author: Gonçalo Silva (GoncaloPT)
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AirwatchSocketWorkaroundPlugin